language: c
dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get install -q postgresql-server-dev-9.3 libcunit1-dev valgrind
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - sh .install-lazperf.sh
  - sh .install-libght.sh
  - npm install -g eclint@1.1.5

addons:
  postgresql: "9.3" # for "installcheck"
  apt:
    packages:
      - postgresql-9.3-postgis-2.3

# Note: Valgrind currently reports many problems when libght is enabled. So for
# now, and until the problems are fixed, we just run the unit tests with libght
# enabled.

script:
  - eclint check * */* */cunit/*
  - ./tools/build-install.sh --with-lazperf=/usr/local --with-libght=/usr/local && make check
  - ./tools/build-install.sh --with-lazperf=/usr/local --without-libght && ./tools/valgrind.sh
  - make installcheck || { cat pgsql/regression.diffs && false; }
  - (cd tools/benchmark_compression && sh compression_benchmark.sh)
